name: publish images to docker

on:
  push:
    branches: ["main"]
  pull_request:
    types: [ closed ]
  workflow_dispatch:

env:

  REGISTRY: docker.io
  BACKEND_IMAGE_NAME: lotusbackend
  FRONTEND_IMAGE_NAME: lotusfrontend
  GUIDANCE_IMAGE_NAME: lotusguidance
  INGESTION_IMAGE_NAME: lotusingestion
  IMAGE_TAG: 1.0.${{ github.run_number }} 

jobs: 
  build-push-lotus-backend-docker: 
    if: github.event.pull_request.merged == true
    name: Build and push Lotus backend docker image to registry
    runs-on: ubuntu-latest 
    steps: 
    - name: checkout repo 
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}

    - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v2
        with:
          working-directory: backend
          context: ./backend
          dockerfile: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # SHOULD BE ABLE TO BUILD WITHOUT REFERENCE TO ENV FILE 
          # UNCOMMENT IF REFERENCE IS NEEDED
          # env_file:
          #   - ./env/.env.prod.example

  build-push-lotus-frontend-docker: 
    if: github.event.pull_request.merged == true
    name: Build and push Lotus backend docker image to registry
    runs-on: ubuntu-latest 
    steps: 
    - name: checkout repo 
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}

    - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          dockerfile: Dockerfile
          # SHOULD BE ABLE TO BUILD WITHOUT REFERENCE TO ENV FILE 
          # UNCOMMENT IF REFERENCE IS NEEDED
          # env_file:
          #   - ./env/.env.prod.example
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build-push-lotus-ingestion-docker:  
    if: github.event.pull_request.merged == true
    name: Build and push Lotus backend docker image to registry
    runs-on: ubuntu-latest 
    steps: 
    - name: checkout repo 
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.INGESTION_IMAGE_NAME }}

    - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v2
        with:
          context: ./go/event-ingestion
          dockerfile: Dockerfile
          # SHOULD BE ABLE TO BUILD WITHOUT REFERENCE TO ENV FILE 
          # UNCOMMENT IF REFERENCE IS NEEDED
          # env_file:
          #   - ./env/.env.prod.example
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  

  build-push-lotus-guidance-docker: 
    if: github.event.pull_request.merged == true
    name: Build and push Lotus backend docker image to registry
    runs-on: ubuntu-latest 
    steps: 
    - name: checkout repo 
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.GUIDANCE_IMAGE_NAME }}

    - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v2
        with:
          context: ./go/event-guidance
          dockerfile: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}